### ISSUE TITLE
Fix deprecated `test-on-native-only`

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/anyio-feedstock#59]
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

I do have some suggestions for making it better though...

For **recipe**:

 * In conda-forge.yml: [`$.test_on_native_only`](https://conda-forge.org/docs/maintainer/conda_forge_yml/#test-on-native-only) `=` `True`.
    > 'Test On Native Only' is deprecated.
    > This was used for disabling testing for cross-compiling.

    > ```warning
    > This has been deprecated in favor of the top-level `test` field.
    > It is now mapped to `test: native_and_emulated`.
    > ```
    <details>
    <summary>Schema</summary>

    ```json
    {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "null"
        }
      ],
      "default": false,
      "deprecated": true,
      "title": "Test On Native Only"
    }
    ```

    </details>

_Originally posted by @conda-forge-webservices[bot] in https://github.com/conda-forge/anyio-feedstock/issues/56#issuecomment-2152636182_

**Comment by bollwyvl** [comment]
Fixed in https://github.com/conda-forge/anyio-feedstock/pull/56
